[package]
name = "StarTracker-rustc"
version = "0.1.0"
edition = "2024"
rust-version = "1.89.0"

[dependencies]
actix-web = "4"
diesel = { version = "2.2.0", features = ["postgres"] }
dotenvy = "0.15"


[[bin]]
name = "StarTracker-rustc"
path = "src/main.rs"